flowchart TB
  subgraph 2 ["`TrackingWebSocketBroadcasterLive`"]
    subgraph 2_wrap[" "]
      subgraph 2_provides [Provides]
        2_provides_0["TrackingWebSocketBroadcaster"]
      end
      style 2_provides stroke:none
    end
    style 2_wrap fill:transparent
    style 2_wrap stroke:none
  end
  style 2 fill:transparent
  subgraph 4 ["`LiveSplitWebSocketBroadcasterLive`"]
    subgraph 4_wrap[" "]
      subgraph 4_provides [Provides]
        4_provides_0["LiveSplitWebSocketBroadcaster"]
      end
      style 4_provides stroke:none
    end
    style 4_wrap fill:transparent
    style 4_wrap stroke:none
  end
  style 4 fill:transparent
  subgraph 6 ["`DungeonRunWebSocketBroadcasterLive`"]
    subgraph 6_wrap[" "]
      subgraph 6_provides [Provides]
        6_provides_0["DungeonRunWebSocketBroadcaster"]
      end
      style 6_provides stroke:none
    end
    style 6_wrap fill:transparent
    style 6_wrap stroke:none
  end
  style 6 fill:transparent
  subgraph 9 ["`LiveSplitWithDependenciesLive`"]
    subgraph 9_wrap[" "]
      subgraph 9_provides [Provides]
        9_provides_0["LiveSplit"]
      end
      style 9_provides stroke:none
    end
    style 9_wrap fill:transparent
    style 9_wrap stroke:none
  end
  style 9 fill:transparent
  subgraph 10 ["`FellowshipWithDependenciesLive`"]
    subgraph 10_wrap[" "]
      subgraph 10_provides [Provides]
        10_provides_0["Fellowship"]
      end
      style 10_provides stroke:none
    end
    style 10_wrap fill:transparent
    style 10_wrap stroke:none
  end
  style 10 fill:transparent
  subgraph 11 ["`PersistenceLive`"]
    subgraph 11_wrap[" "]
      subgraph 11_provides [Provides]
        11_provides_0["AbilityDAO"]
        11_provides_1["AppSettingsDAO"]
        11_provides_2["ConfigurationDAO"]
        11_provides_3["DungeonDAO"]
        11_provides_4["DungeonRunDAO"]
        11_provides_5["DungeonRunObservationDAO"]
        11_provides_6["EncounterDAO"]
        11_provides_7["UnitDAO"]
      end
      style 11_provides stroke:none
    end
    style 11_wrap fill:transparent
    style 11_wrap stroke:none
  end
  style 11 fill:transparent
  subgraph 12 ["`FellowshipTrackerDependenciesLive`"]
    subgraph 12_wrap[" "]
      subgraph 12_provides [Provides]
        12_provides_0["AbilityDAO"]
        12_provides_1["AppSettingsDAO"]
        12_provides_2["ConfigurationDAO"]
        12_provides_3["DungeonDAO"]
        12_provides_4["DungeonRunDAO"]
        12_provides_5["DungeonRunObservationDAO"]
        12_provides_6["DungeonRunWebSocketBroadcaster"]
        12_provides_7["EncounterDAO"]
        12_provides_8["Fellowship"]
        12_provides_9["LiveSplit"]
        12_provides_10["UnitDAO"]
      end
      style 12_provides stroke:none
    end
    style 12_wrap fill:transparent
    style 12_wrap stroke:none
  end
  style 12 fill:transparent
  subgraph 15 ["`FellowshipTrackerLive`"]
    subgraph 15_wrap[" "]
      subgraph 15_requires [Requires]
        15_requires_0["ConfigurationDAO"]
        15_requires_1["DungeonRunDAO"]
        15_requires_2["DungeonRunObservationDAO"]
        15_requires_3["DungeonRunWebSocketBroadcaster"]
        15_requires_4["Fellowship"]
        15_requires_5["LiveSplit"]
      end
      style 15_requires stroke:none
      subgraph 15_provides [Provides]
        15_provides_0["FellowshipTracker"]
      end
      style 15_provides stroke:none
    end
    style 15_wrap fill:transparent
    style 15_wrap stroke:none
  end
  style 15 fill:transparent
  subgraph 17 ["`FellowshipTrackerWithDependenciesLive`"]
    subgraph 17_wrap[" "]
      subgraph 17_provides [Provides]
        17_provides_0["FellowshipTracker"]
      end
      style 17_provides stroke:none
    end
    style 17_wrap fill:transparent
    style 17_wrap stroke:none
  end
  style 17 fill:transparent
  subgraph 20 ["`AppSettingsWithDependenciesLive`"]
    subgraph 20_wrap[" "]
      subgraph 20_provides [Provides]
        20_provides_0["AppSettings"]
      end
      style 20_provides stroke:none
    end
    style 20_wrap fill:transparent
    style 20_wrap stroke:none
  end
  style 20 fill:transparent
  subgraph 22 ["`ApiServicesDependenciesLive`"]
    subgraph 22_wrap[" "]
      subgraph 22_provides [Provides]
        22_provides_0["AbilityDAO"]
        22_provides_1["AppSettings"]
        22_provides_2["AppSettingsDAO"]
        22_provides_3["ConfigurationDAO"]
        22_provides_4["DungeonDAO"]
        22_provides_5["DungeonRunDAO"]
        22_provides_6["DungeonRunObservationDAO"]
        22_provides_7["EncounterDAO"]
        22_provides_8["LiveSplit"]
        22_provides_9["UnitDAO"]
      end
      style 22_provides stroke:none
    end
    style 22_wrap fill:transparent
    style 22_wrap stroke:none
  end
  style 22 fill:transparent
  subgraph 25 ["`UnitApiServiceLive`"]
    subgraph 25_wrap[" "]
      subgraph 25_requires [Requires]
        25_requires_0["UnitDAO"]
      end
      style 25_requires stroke:none
      subgraph 25_provides [Provides]
        25_provides_0["UnitApiService"]
      end
      style 25_provides stroke:none
    end
    style 25_wrap fill:transparent
    style 25_wrap stroke:none
  end
  style 25 fill:transparent
  subgraph 26 ["`LiveSplitApiServiceLive`"]
    subgraph 26_wrap[" "]
      subgraph 26_requires [Requires]
        26_requires_0["LiveSplit"]
      end
      style 26_requires stroke:none
      subgraph 26_provides [Provides]
        26_provides_0["LiveSplitApiService"]
      end
      style 26_provides stroke:none
    end
    style 26_wrap fill:transparent
    style 26_wrap stroke:none
  end
  style 26 fill:transparent
  subgraph 27 ["`EncounterApiServiceLive`"]
    subgraph 27_wrap[" "]
      subgraph 27_requires [Requires]
        27_requires_0["EncounterDAO"]
      end
      style 27_requires stroke:none
      subgraph 27_provides [Provides]
        27_provides_0["EncounterApiService"]
      end
      style 27_provides stroke:none
    end
    style 27_wrap fill:transparent
    style 27_wrap stroke:none
  end
  style 27 fill:transparent
  subgraph 28 ["`DungeonRunApiServiceLive`"]
    subgraph 28_wrap[" "]
      subgraph 28_requires [Requires]
        28_requires_0["ConfigurationDAO"]
        28_requires_1["DungeonRunObservationDAO"]
      end
      style 28_requires stroke:none
      subgraph 28_provides [Provides]
        28_provides_0["DungeonRunApiService"]
      end
      style 28_provides stroke:none
    end
    style 28_wrap fill:transparent
    style 28_wrap stroke:none
  end
  style 28 fill:transparent
  subgraph 29 ["`DungeonApiServiceLive`"]
    subgraph 29_wrap[" "]
      subgraph 29_requires [Requires]
        29_requires_0["DungeonDAO"]
      end
      style 29_requires stroke:none
      subgraph 29_provides [Provides]
        29_provides_0["DungeonApiService"]
      end
      style 29_provides stroke:none
    end
    style 29_wrap fill:transparent
    style 29_wrap stroke:none
  end
  style 29 fill:transparent
  subgraph 30 ["`ConfigurationApiServiceLive`"]
    subgraph 30_wrap[" "]
      subgraph 30_requires [Requires]
        30_requires_0["ConfigurationDAO"]
      end
      style 30_requires stroke:none
      subgraph 30_provides [Provides]
        30_provides_0["ConfigurationApiService"]
      end
      style 30_provides stroke:none
    end
    style 30_wrap fill:transparent
    style 30_wrap stroke:none
  end
  style 30 fill:transparent
  subgraph 31 ["`AppSettingsApiServiceLive`"]
    subgraph 31_wrap[" "]
      subgraph 31_requires [Requires]
        31_requires_0["AppSettings"]
      end
      style 31_requires stroke:none
      subgraph 31_provides [Provides]
        31_provides_0["AppSettingsApiService"]
      end
      style 31_provides stroke:none
    end
    style 31_wrap fill:transparent
    style 31_wrap stroke:none
  end
  style 31 fill:transparent
  subgraph 32 ["`AbilityApiServiceLive`"]
    subgraph 32_wrap[" "]
      subgraph 32_requires [Requires]
        32_requires_0["AbilityDAO"]
      end
      style 32_requires stroke:none
      subgraph 32_provides [Provides]
        32_provides_0["AbilityApiService"]
      end
      style 32_provides stroke:none
    end
    style 32_wrap fill:transparent
    style 32_wrap stroke:none
  end
  style 32 fill:transparent
  subgraph 33 ["`ApiServicesLive`"]
    subgraph 33_wrap[" "]
      subgraph 33_requires [Requires]
        33_requires_0["AbilityDAO"]
        33_requires_1["AppSettings"]
        33_requires_2["ConfigurationDAO"]
        33_requires_3["DungeonDAO"]
        33_requires_4["DungeonRunObservationDAO"]
        33_requires_5["EncounterDAO"]
        33_requires_6["LiveSplit"]
        33_requires_7["UnitDAO"]
      end
      style 33_requires stroke:none
      subgraph 33_provides [Provides]
        33_provides_0["AbilityApiService"]
        33_provides_1["AppSettingsApiService"]
        33_provides_2["ConfigurationApiService"]
        33_provides_3["DungeonApiService"]
        33_provides_4["DungeonRunApiService"]
        33_provides_5["EncounterApiService"]
        33_provides_6["LiveSplitApiService"]
        33_provides_7["UnitApiService"]
      end
      style 33_provides stroke:none
    end
    style 33_wrap fill:transparent
    style 33_wrap stroke:none
  end
  style 33 fill:transparent
  subgraph 35 ["`ApiServicesWithDependenciesLive`"]
    subgraph 35_wrap[" "]
      subgraph 35_provides [Provides]
        35_provides_0["AbilityApiService"]
        35_provides_1["AppSettingsApiService"]
        35_provides_2["ConfigurationApiService"]
        35_provides_3["DungeonApiService"]
        35_provides_4["DungeonRunApiService"]
        35_provides_5["EncounterApiService"]
        35_provides_6["LiveSplitApiService"]
        35_provides_7["UnitApiService"]
      end
      style 35_provides stroke:none
    end
    style 35_wrap fill:transparent
    style 35_wrap stroke:none
  end
  style 35 fill:transparent
  subgraph 37 ["`ApiServerDependenciesLive`"]
    subgraph 37_wrap[" "]
      subgraph 37_provides [Provides]
        37_provides_0["AbilityApiService"]
        37_provides_1["AppSettingsApiService"]
        37_provides_3["ConfigurationApiService"]
        37_provides_5["DungeonApiService"]
        37_provides_6["DungeonRunApiService"]
        37_provides_7["DungeonRunWebSocketBroadcaster"]
        37_provides_8["EncounterApiService"]
        37_provides_9["FellowshipTracker"]
        37_provides_14["LiveSplitApiService"]
        37_provides_15["LiveSplitWebSocketBroadcaster"]
        37_provides_19["TrackingWebSocketBroadcaster"]
        37_provides_20["UnitApiService"]
      end
      style 37_provides stroke:none
    end
    style 37_wrap fill:transparent
    style 37_wrap stroke:none
  end
  style 37 fill:transparent
  subgraph 43 ["`TrackingRoutes`"]
    subgraph 43_wrap[" "]
      subgraph 43_requires [Requires]
        43_requires_3["TrackingWebSocketBroadcaster"]
      end
      style 43_requires stroke:none
    end
    style 43_wrap fill:transparent
    style 43_wrap stroke:none
  end
  style 43 fill:transparent
  subgraph 44 ["`LiveSplitRoutes`"]
    subgraph 44_wrap[" "]
      subgraph 44_requires [Requires]
        44_requires_3["LiveSplitWebSocketBroadcaster"]
      end
      style 44_requires stroke:none
    end
    style 44_wrap fill:transparent
    style 44_wrap stroke:none
  end
  style 44 fill:transparent
  subgraph 45 ["`DungeonRunEventsRoutes`"]
    subgraph 45_wrap[" "]
      subgraph 45_requires [Requires]
        45_requires_3["DungeonRunWebSocketBroadcaster"]
      end
      style 45_requires stroke:none
    end
    style 45_wrap fill:transparent
    style 45_wrap stroke:none
  end
  style 45 fill:transparent
  subgraph 46 ["`WebsocketRoutes`"]
    subgraph 46_wrap[" "]
      subgraph 46_requires [Requires]
        46_requires_3["DungeonRunWebSocketBroadcaster"]
        46_requires_4["LiveSplitWebSocketBroadcaster"]
        46_requires_5["TrackingWebSocketBroadcaster"]
      end
      style 46_requires stroke:none
    end
    style 46_wrap fill:transparent
    style 46_wrap stroke:none
  end
  style 46 fill:transparent
  subgraph 48 ["`UnitsApiLive`"]
    subgraph 48_wrap[" "]
      subgraph 48_requires [Requires]
        48_requires_0["UnitApiService"]
      end
      style 48_requires stroke:none
    end
    style 48_wrap fill:transparent
    style 48_wrap stroke:none
  end
  style 48 fill:transparent
  subgraph 50 ["`TrackingApiLive`"]
    subgraph 50_wrap[" "]
      subgraph 50_requires [Requires]
        50_requires_0["FellowshipTracker"]
      end
      style 50_requires stroke:none
    end
    style 50_wrap fill:transparent
    style 50_wrap stroke:none
  end
  style 50 fill:transparent
  subgraph 52 ["`LiveSplitApiLive`"]
    subgraph 52_wrap[" "]
      subgraph 52_requires [Requires]
        52_requires_0["LiveSplitApiService"]
      end
      style 52_requires stroke:none
    end
    style 52_wrap fill:transparent
    style 52_wrap stroke:none
  end
  style 52 fill:transparent
  subgraph 54 ["`EncountersApiLive`"]
    subgraph 54_wrap[" "]
      subgraph 54_requires [Requires]
        54_requires_0["EncounterApiService"]
      end
      style 54_requires stroke:none
    end
    style 54_wrap fill:transparent
    style 54_wrap stroke:none
  end
  style 54 fill:transparent
  subgraph 56 ["`DungeonsApiLive`"]
    subgraph 56_wrap[" "]
      subgraph 56_requires [Requires]
        56_requires_0["DungeonApiService"]
      end
      style 56_requires stroke:none
    end
    style 56_wrap fill:transparent
    style 56_wrap stroke:none
  end
  style 56 fill:transparent
  subgraph 58 ["`DungeonRunsApiLive`"]
    subgraph 58_wrap[" "]
      subgraph 58_requires [Requires]
        58_requires_0["DungeonRunApiService"]
      end
      style 58_requires stroke:none
    end
    style 58_wrap fill:transparent
    style 58_wrap stroke:none
  end
  style 58 fill:transparent
  subgraph 60 ["`ConfigurationsApiLive`"]
    subgraph 60_wrap[" "]
      subgraph 60_requires [Requires]
        60_requires_0["ConfigurationApiService"]
      end
      style 60_requires stroke:none
    end
    style 60_wrap fill:transparent
    style 60_wrap stroke:none
  end
  style 60 fill:transparent
  subgraph 62 ["`AppSettingsApiLive`"]
    subgraph 62_wrap[" "]
      subgraph 62_requires [Requires]
        62_requires_0["AppSettingsApiService"]
      end
      style 62_requires stroke:none
    end
    style 62_wrap fill:transparent
    style 62_wrap stroke:none
  end
  style 62 fill:transparent
  subgraph 64 ["`AbilitiesApiLive`"]
    subgraph 64_wrap[" "]
      subgraph 64_requires [Requires]
        64_requires_0["AbilityApiService"]
      end
      style 64_requires stroke:none
    end
    style 64_wrap fill:transparent
    style 64_wrap stroke:none
  end
  style 64 fill:transparent
  subgraph 67 ["`HttpApiRoutes`"]
    subgraph 67_wrap[" "]
      subgraph 67_requires [Requires]
        67_requires_0["AbilityApiService"]
        67_requires_1["AppSettingsApiService"]
        67_requires_2["ConfigurationApiService"]
        67_requires_3["DungeonApiService"]
        67_requires_4["DungeonRunApiService"]
        67_requires_5["EncounterApiService"]
        67_requires_6["FellowshipTracker"]
        67_requires_11["LiveSplitApiService"]
        67_requires_13["UnitApiService"]
      end
      style 67_requires stroke:none
    end
    style 67_wrap fill:transparent
    style 67_wrap stroke:none
  end
  style 67 fill:transparent
  subgraph 70 ["`ApiRoutes`"]
    subgraph 70_wrap[" "]
      subgraph 70_requires [Requires]
        70_requires_0["AbilityApiService"]
        70_requires_1["AppSettingsApiService"]
        70_requires_2["ConfigurationApiService"]
        70_requires_3["DungeonApiService"]
        70_requires_4["DungeonRunApiService"]
        70_requires_5["EncounterApiService"]
        70_requires_6["FellowshipTracker"]
        70_requires_11["LiveSplitApiService"]
        70_requires_15["DungeonRunWebSocketBroadcaster"]
        70_requires_16["LiveSplitWebSocketBroadcaster"]
        70_requires_17["TrackingWebSocketBroadcaster"]
        70_requires_18["UnitApiService"]
      end
      style 70_requires stroke:none
    end
    style 70_wrap fill:transparent
    style 70_wrap stroke:none
  end
  style 70 fill:transparent
  subgraph 72 ["`ApiServer`"]
    subgraph 72_wrap[" "]
      subgraph 72_requires [Requires]
        72_requires_0["AbilityApiService"]
        72_requires_1["AppSettingsApiService"]
        72_requires_2["ConfigurationApiService"]
        72_requires_3["DungeonApiService"]
        72_requires_4["DungeonRunApiService"]
        72_requires_5["DungeonRunWebSocketBroadcaster"]
        72_requires_6["EncounterApiService"]
        72_requires_7["FellowshipTracker"]
        72_requires_12["LiveSplitApiService"]
        72_requires_13["LiveSplitWebSocketBroadcaster"]
        72_requires_15["TrackingWebSocketBroadcaster"]
        72_requires_16["UnitApiService"]
      end
      style 72_requires stroke:none
    end
    style 72_wrap fill:transparent
    style 72_wrap stroke:none
  end
  style 72 fill:transparent
  12_provides_0 -.-> 11_provides_0
  12_provides_1 -.-> 11_provides_1
  12_provides_2 -.-> 11_provides_2
  12_provides_3 -.-> 11_provides_3
  12_provides_4 -.-> 11_provides_4
  12_provides_5 -.-> 11_provides_5
  12_provides_7 -.-> 11_provides_6
  12_provides_10 -.-> 11_provides_7
  12_provides_8 -.-> 10_provides_0
  12_provides_9 -.-> 9_provides_0
  12_provides_6 -.-> 6_provides_0
  22_provides_0 -.-> 11_provides_0
  22_provides_2 -.-> 11_provides_1
  22_provides_3 -.-> 11_provides_2
  22_provides_4 -.-> 11_provides_3
  22_provides_5 -.-> 11_provides_4
  22_provides_6 -.-> 11_provides_5
  22_provides_7 -.-> 11_provides_6
  22_provides_9 -.-> 11_provides_7
  22_provides_1 -.-> 20_provides_0
  22_provides_8 -.-> 9_provides_0
  33_requires_0 -.-> 32_requires_0
  33_provides_0 -.-> 32_provides_0
  33_requires_1 -.-> 31_requires_0
  33_provides_1 -.-> 31_provides_0
  33_requires_2 -.-> 30_requires_0
  33_provides_2 -.-> 30_provides_0
  33_requires_3 -.-> 29_requires_0
  33_provides_3 -.-> 29_provides_0
  33_requires_2 -.-> 28_requires_0
  33_requires_4 -.-> 28_requires_1
  33_provides_4 -.-> 28_provides_0
  33_requires_5 -.-> 27_requires_0
  33_provides_5 -.-> 27_provides_0
  33_requires_6 -.-> 26_requires_0
  33_provides_6 -.-> 26_provides_0
  33_requires_7 -.-> 25_requires_0
  33_provides_7 -.-> 25_provides_0
  37_provides_0 -.-> 35_provides_0
  37_provides_1 -.-> 35_provides_1
  37_provides_3 -.-> 35_provides_2
  37_provides_5 -.-> 35_provides_3
  37_provides_6 -.-> 35_provides_4
  37_provides_8 -.-> 35_provides_5
  37_provides_14 -.-> 35_provides_6
  37_provides_20 -.-> 35_provides_7
  37_provides_9 -.-> 17_provides_0
  37_provides_7 -.-> 6_provides_0
  37_provides_15 -.-> 4_provides_0
  37_provides_19 -.-> 2_provides_0
  46_requires_3 -.-> 45_requires_3
  46_requires_4 -.-> 44_requires_3
  46_requires_5 -.-> 43_requires_3
  72_requires_0 -.-> 70_requires_0
  72_requires_1 -.-> 70_requires_1
  72_requires_2 -.-> 70_requires_2
  72_requires_3 -.-> 70_requires_3
  72_requires_4 -.-> 70_requires_4
  72_requires_6 -.-> 70_requires_5
  72_requires_7 -.-> 70_requires_6
  72_requires_12 -.-> 70_requires_11
  72_requires_16 -.-> 70_requires_18
  17_provides_0 -.-> 15_provides_0
  35_provides_0 -.-> 33_provides_0
  35_provides_1 -.-> 33_provides_1
  35_provides_2 -.-> 33_provides_2
  35_provides_3 -.-> 33_provides_3
  35_provides_4 -.-> 33_provides_4
  35_provides_5 -.-> 33_provides_5
  35_provides_6 -.-> 33_provides_6
  35_provides_7 -.-> 33_provides_7
  67_requires_13 -.-> 48_requires_0
  67_requires_6 -.-> 50_requires_0
  67_requires_11 -.-> 52_requires_0
  67_requires_5 -.-> 54_requires_0
  67_requires_3 -.-> 56_requires_0
  67_requires_4 -.-> 58_requires_0
  67_requires_2 -.-> 60_requires_0
  67_requires_1 -.-> 62_requires_0
  67_requires_0 -.-> 64_requires_0
  70_requires_0 -.-> 67_requires_0
  70_requires_1 -.-> 67_requires_1
  70_requires_2 -.-> 67_requires_2
  70_requires_3 -.-> 67_requires_3
  70_requires_4 -.-> 67_requires_4
  70_requires_5 -.-> 67_requires_5
  70_requires_6 -.-> 67_requires_6
  70_requires_11 -.-> 67_requires_11
  70_requires_18 -.-> 67_requires_13
  70_requires_15 -.-> 46_requires_3
  70_requires_16 -.-> 46_requires_4
  70_requires_17 -.-> 46_requires_5
