/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackgroundJobsRouteImport } from './routes/background-jobs'
import { Route as FellowshipLogsRouteImport } from './routes/fellowship-logs'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundJobsRoute = BackgroundJobsRouteImport.update({
  id: '/background-jobs',
  path: '/background-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FellowshipLogsRoute = FellowshipLogsRouteImport.update({
  id: '/fellowship-logs',
  path: '/fellowship-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/background-jobs': typeof BackgroundJobsRoute
  '/fellowship-logs': typeof FellowshipLogsRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/background-jobs': typeof BackgroundJobsRoute
  '/fellowship-logs': typeof FellowshipLogsRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/background-jobs': typeof BackgroundJobsRoute
  '/fellowship-logs': typeof FellowshipLogsRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/background-jobs' | '/fellowship-logs' | '/history' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/background-jobs' | '/fellowship-logs' | '/history' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/background-jobs'
    | '/fellowship-logs'
    | '/history'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackgroundJobsRoute: typeof BackgroundJobsRoute
  FellowshipLogsRoute: typeof FellowshipLogsRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background-jobs': {
      id: '/background-jobs'
      path: '/background-jobs'
      fullPath: '/background-jobs'
      preLoaderRoute: typeof BackgroundJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fellowship-logs': {
      id: '/fellowship-logs'
      path: '/fellowship-logs'
      fullPath: '/fellowship-logs'
      preLoaderRoute: typeof FellowshipLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackgroundJobsRoute: BackgroundJobsRoute,
  FellowshipLogsRoute: FellowshipLogsRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
