export const API_EVENT_CONNECTION_STATE = {
  CONNECTED: "CONNECTED",
  CONNECTING: "CONNECTING",
  DISCONNECTED: "DISCONNECTED",
  ERROR: "ERROR",
} as const;

export type ApiEventConnectionState =
  (typeof API_EVENT_CONNECTION_STATE)[keyof typeof API_EVENT_CONNECTION_STATE];
